# Generated by Django 4.2 for Campus Lost & Found System

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name or title of the lost or found item', max_length=200)),
                ('description', models.TextField(help_text='Detailed description, distinct features, marks, or circumstances')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('ID Card', 'ID Card'), ('Wallet', 'Wallet'), ('Keys', 'Keys'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Documents', 'Documents'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Returned', 'Returned')], default='Lost', max_length=20)),
                ('location', models.CharField(help_text='Specific campus building, room, cafeteria, or sports complex location', max_length=200)),
                ('date_lost_found', models.DateField(help_text='Date when the item was misplaced or discovered')),
                ('reported_by', models.CharField(help_text='Full name of student or campus staff reporting this item', max_length=150)),
                ('student_email', models.EmailField(help_text='Official college or contact email address', max_length=254)),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999' or 10 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('image_url', models.URLField(blank=True, help_text='Optional web URL of photo of the item', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was initially submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the report was last updated')),
            ],
            options={
                'verbose_name': 'Lost & Found Item',
                'verbose_name_plural': 'Lost & Found Items',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
